.\" Manpage for hermes (zeus cache server process).
.\" Contact vgeshiktor@gmail.com to correct errors or typos.
.TH man 1 "08 Nov 2015" "1.0" "hermes man page"
.SH NAME
.B hermes 
\- handles communication for zeus cache db server
.SH SYNOPSIS
.B hermes
[\fB\-\-help\fR]
[\fB\-h\fR\]
[\fB\-\-version\fR\]
[\fB\-v\fR\]
.SH DESCRIPTION
.B hermes 
is communication server process used in zeus cache db server.
.SH OPTIONS
.TP
.BR \-\-help ", " \-h
shows command line options help
.TP
.BR \-\-version ", " \-v
shows version info
.SH SEE ALSO
zeus(1), heracles(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Vadim Geshiktor (vgeshiktor@gmail.com)
